import { initializeApp } from "https://www.gstatic.com/firebasejs/11.9.1/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.9.1/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, onSnapshot, query, where, runTransaction, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.9.1/firebase-firestore.js";
import { firebaseConfig, STUDENT_DOMAIN } from "./firebase-config.mjs";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(); provider.setCustomParameters({prompt:"select_account"});
const $=s=>document.querySelector(s); let user=null,events=[],myRegs=new Map(),settings={maxRegistrations:1,allowCancellation:false},filter="open",chosen=null;
const safe=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const tdtuEmail=e=>{const value=String(e||"").toLowerCase();return value.endsWith(STUDENT_DOMAIN)||value.endsWith("@tdtu.edu.vn")};
const participantType=e=>String(e||"").toLowerCase().endsWith(STUDENT_DOMAIN)?"Sinh viên":String(e||"").toLowerCase().endsWith("@tdtu.edu.vn")?"Giảng viên/Nhân sự":"Admin";
async function participantAccess(u){if(tdtuEmail(u.email))return true;return (await getDoc(doc(db,"admins",u.email.toLowerCase()))).exists()}
const show=(msg,type="")=>{const n=$("#notice");n.textContent=msg;n.className=`notice ${type}`;n.classList.remove("hidden");setTimeout(()=>n.classList.add("hidden"),6000)};
const formatDate=e=>{try{return new Intl.DateTimeFormat("vi-VN",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${e.date}T00:00:00`))}catch{return e.date}};
const millis=v=>v?.toDate?v.toDate().getTime():(v?new Date(v).getTime():null);
function stateOf(e){if(myRegs.has(e.id))return"mine"; if(e.status!=="open")return"closed"; const now=Date.now(),open=millis(e.openAt)??0,close=millis(e.closeAt)??Infinity;if(now<open||now>close)return"closed";if((e.registeredCount||0)>=(e.capacity||0))return"full";return"open"}
function render(){const count=myRegs.size;$("#quotaValue").textContent=`${count}/${settings.maxRegistrations||1}`;let list=events.filter(e=>filter==="all"||filter==="mine"?stateOf(e)==="mine":stateOf(e)==="open");$("#eventSummary").textContent=`${list.length} sự kiện phù hợp`;const grid=$("#eventGrid");if(!list.length){grid.innerHTML='<div class="card empty">Chưa có sự kiện phù hợp.</div>';return}grid.innerHTML=list.map(e=>{const st=stateOf(e),used=e.registeredCount||0,cap=e.capacity||0,left=Math.max(0,cap-used),pct=cap?Math.min(100,used/cap*100):0,label={open:"CÒN CHỖ",full:"ĐÃ ĐỦ",mine:"ĐÃ ĐĂNG KÝ",closed:"ĐÃ ĐÓNG"}[st];return `<article class="card event"><div class="event-top"><div><span class="tag ${st}">${label}</span><h3>${safe(e.title)}</h3></div></div><div class="meta"><span>◷ ${safe(formatDate(e))} · ${safe(e.startTime||"")}${e.endTime?`–${safe(e.endTime)}`:""}</span><span>⌖ ${safe(e.location||"Chưa cập nhật địa điểm")}</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="capacity"><span>${used}/${cap} người tham gia</span><b>Còn ${left} chỗ</b></div><div class="event-actions"><button class="btn" data-view="${e.id}">Xem chi tiết</button>${st==="mine"&&settings.allowCancellation?`<button class="btn btn-danger" data-cancel="${e.id}">Hủy đăng ký</button>`:`<button class="btn btn-primary" data-register="${e.id}" ${st!=="open"?"disabled":""}>Đăng ký</button>`}</div></article>`}).join("")}
async function loadData(){onSnapshot(doc(db,"settings","main"),s=>{if(s.exists())settings={...settings,...s.data()};render()});onSnapshot(query(collection(db,"registrations"),where("uid","==",user.uid)),s=>{myRegs=new Map(s.docs.map(d=>[d.data().eventId,{id:d.id,...d.data()}]));render()});onSnapshot(collection(db,"events"),s=>{events=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));render()})}
async function register(eventId){if(myRegs.size>=(settings.maxRegistrations||1))return show(`Bạn đã đăng ký đủ ${settings.maxRegistrations||1} sự kiện.`,"error");const eRef=doc(db,"events",eventId),rRef=doc(db,"registrations",`${user.uid}_${eventId}`),sRef=doc(db,"studentStats",user.uid);try{await runTransaction(db,async tx=>{const es=await tx.get(eRef),rs=await tx.get(rRef),ss=await tx.get(sRef),cs=await tx.get(doc(db,"settings","main"));if(!es.exists())throw Error("Sự kiện không tồn tại.");if(rs.exists())throw Error("Bạn đã đăng ký sự kiện này.");const e=es.data(),cfg=cs.exists()?cs.data():settings,current=ss.exists()?ss.data():{count:0,eventIds:[]};if(stateOf(e)!=="open")throw Error("Sự kiện đã đủ, chưa mở hoặc đã đóng.");if((current.count||0)>=(cfg.maxRegistrations||1))throw Error("Bạn đã đạt giới hạn đăng ký.");const identifier=user.email.split("@")[0].toUpperCase(),type=participantType(user.email);tx.update(eRef,{registeredCount:(e.registeredCount||0)+1,updatedAt:serverTimestamp()});tx.set(rRef,{uid:user.uid,email:user.email.toLowerCase(),mssv:identifier,identifier,participantType:type,name:user.displayName||"",eventId,eventTitle:e.title,eventDate:e.date,createdAt:serverTimestamp()});tx.set(sRef,{uid:user.uid,email:user.email.toLowerCase(),participantType:type,count:(current.count||0)+1,eventIds:[...(current.eventIds||[]),eventId],updatedAt:serverTimestamp()})});show("Đăng ký thành công.","success")}catch(err){show(err.message||"Không thể đăng ký.","error")}}
async function cancel(eventId){if(!settings.allowCancellation)return;const eRef=doc(db,"events",eventId),rRef=doc(db,"registrations",`${user.uid}_${eventId}`),sRef=doc(db,"studentStats",user.uid);try{await runTransaction(db,async tx=>{const es=await tx.get(eRef),rs=await tx.get(rRef),ss=await tx.get(sRef);if(!es.exists()||!rs.exists()||!ss.exists())throw Error("Không tìm thấy đăng ký.");const e=es.data(),st=ss.data();tx.update(eRef,{registeredCount:Math.max(0,(e.registeredCount||0)-1),updatedAt:serverTimestamp()});tx.delete(rRef);tx.set(sRef,{...st,count:Math.max(0,(st.count||0)-1),eventIds:(st.eventIds||[]).filter(x=>x!==eventId),updatedAt:serverTimestamp()})});show("Đã hủy đăng ký.","success")}catch(err){show(err.message||"Không thể hủy.","error")}}
function openDetail(id){chosen=events.find(e=>e.id===id);if(!chosen)return;$("#detailTitle").textContent=chosen.title;$("#detailBody").innerHTML=`<div class="meta"><span><b>Thời gian:</b> ${safe(formatDate(chosen))}, ${safe(chosen.startTime||"")}${chosen.endTime?`–${safe(chosen.endTime)}`:""}</span><span><b>Địa điểm:</b> ${safe(chosen.location||"Chưa cập nhật")}</span></div><p>${safe(chosen.description||"Không có mô tả.")}</p><div class="notice">Còn ${Math.max(0,chosen.capacity-(chosen.registeredCount||0))} chỗ. Bạn được đăng ký tối đa ${settings.maxRegistrations||1} sự kiện.</div>`;$("#confirmBtn").disabled=stateOf(chosen)!=="open";$("#detailDialog").showModal()}
$("#loginBtn").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){show("Không thể đăng nhập Google.","error")}};$("#logoutBtn").onclick=()=>signOut(auth);document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.close!==undefined)$("#detailDialog").close();if(b.dataset.view)openDetail(b.dataset.view);if(b.dataset.register)openDetail(b.dataset.register);if(b.dataset.cancel&&confirm("Hủy đăng ký sự kiện này?"))cancel(b.dataset.cancel);if(b.classList.contains("filter")){document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()}});$("#confirmBtn").onclick=async()=>{if(chosen){$("#detailDialog").close();await register(chosen.id)}};
onAuthStateChanged(auth,async u=>{if(!u){user=null;$("#loginCard").classList.remove("hidden");$("#studentApp").classList.add("hidden");$("#logoutBtn").classList.add("hidden");return}if(!u.emailVerified||!(await participantAccess(u))){await signOut(auth);alert("Chỉ chấp nhận email TDTU hoặc tài khoản Google đã được cấp quyền Admin.");return}user=u;$("#accountEmail").textContent=`${u.email} · ${participantType(u.email)}`;$("#loginCard").classList.add("hidden");$("#studentApp").classList.remove("hidden");$("#logoutBtn").classList.remove("hidden");loadData()});
