import{initializeApp}from"https://www.gstatic.com/firebasejs/11.9.1/firebase-app.js";import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/11.9.1/firebase-auth.js";import{getFirestore,collection,doc,getDoc,getDocs,setDoc,onSnapshot,query,where,serverTimestamp}from"https://www.gstatic.com/firebasejs/11.9.1/firebase-firestore.js";import{firebaseConfig,STUDENT_DOMAIN,OWNER_EMAIL}from"../firebase-config.mjs";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s),sessionId=new URLSearchParams(location.search).get("event");let user,session,assignment,unsubscribe,isManager=false,managerName="",cameraStream=null,cameraControls=null,cameraReader=null,cameraRequest=0,pendingPhoto="",lastDecoded="",lastDecodedAt=0;const esc=v=>String(v??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));const stamp=v=>v?.toDate?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(v.toDate()):"—";function notice(t){$("#notice").textContent=t;$("#notice").classList.remove("hidden");setTimeout(()=>$("#notice").classList.add("hidden"),3500)}
async function start(){if(!sessionId)return notice("Liên kết điểm danh không hợp lệ.");const s=await getDoc(doc(db,"attendanceSessions",sessionId));if(!s.exists())return notice("Không tìm thấy sự kiện.");session={id:s.id,...s.data()};if(isManager){assignment={active:true,role:"leader",name:managerName||user.displayName||user.email};}else{const a=await getDoc(doc(db,"scannerAssignments",sessionId+"_"+user.email));assignment=a.data();if(!assignment?.active)return notice("Bạn chưa được cấp quyền quét sự kiện này.");}$("#app").classList.remove("hidden");$("#title").textContent=session.title;$("#meta").textContent=[session.date,session.location].filter(Boolean).join(" · ");const finalized=session.status==="finalized";const blocked=finalized&&!isManager;$("#closedMessage").classList.toggle("hidden",!blocked);$("#scannerArea").classList.toggle("hidden",blocked);if(blocked)return;$("#scanForm").classList.toggle("hidden",session.status!=="open");$(".camera-card").classList.toggle("hidden",session.status!=="open");$("#roleText").textContent=isManager?"Quyền: Quản trị hệ thống":session.status==="ended"?"Sự kiện đã kết thúc — chỉ được xem danh sách.":assignment.role==="leader"?"Quyền: SV Leader":"Quyền: SV quét";listenRows()}
function listenRows(){if(unsubscribe)unsubscribe();const qy=assignment.role==="leader"?query(collection(db,"checkins"),where("sessionId","==",session.id)):query(collection(db,"checkins"),where("scannerUid","==",user.uid));unsubscribe=onSnapshot(qy,s=>{const rows=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.sessionId===session.id&&!x.deletedAt);$("#rows").innerHTML=rows.map(x=>`<tr><td>${esc(x.mssv)}</td><td>${esc(x.name)}</td><td>${stamp(x.checkedAt)}</td><td>${assignment.role==="leader"&&session.status==="open"?`<button class="att-btn danger" data-delete="${x.id}">Xóa</button>`:""}</td></tr>`).join("")||'<tr><td colspan="4">Chưa có lượt điểm danh.</td></tr>'},e=>notice(e.message))}
onAuthStateChanged(auth,async u=>{user=u;$("#loginBtn").classList.toggle("hidden",!!u);$("#logoutBtn").classList.toggle("hidden",!u);$("#account").textContent=u?.email||"";if(!u)return $("#app").classList.add("hidden");const adminDoc=u.email===OWNER_EMAIL?null:await getDoc(doc(db,"admins",u.email.toLowerCase()));isManager=u.email===OWNER_EMAIL||!!adminDoc?.exists();if(!isManager&&!u.email.endsWith(STUDENT_DOMAIN)){await signOut(auth);return notice("Tài khoản chưa được cấp quyền truy cập.");}if(isManager){const profileDoc=await getDoc(doc(db,"profiles",u.uid));managerName=String(adminDoc?.data()?.name||profileDoc.data()?.name||u.displayName||u.email).trim();$("#account").textContent=managerName+" · "+u.email;}start().catch(e=>notice(e.message))});$("#loginBtn").onclick=()=>signInWithPopup(auth,provider).catch(e=>notice(e.message));$("#logoutBtn").onclick=()=>signOut(auth);

function setScanStatus(type,title,detail=""){const box=$("#scanStatus");box.className="scan-status"+(type?" "+type:"");box.innerHTML="<b>"+esc(title)+"</b><span>"+esc(detail)+"</span>"}
function feedback(kind="success"){try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=kind==="duplicate"?180:880;g.gain.setValueAtTime(.12,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.start();o.stop(a.currentTime+.17)}catch{}if(navigator.vibrate)navigator.vibrate(kind==="duplicate"?[120,70,120]:80)}
function validMssv(v){return /^(?=.{8,12}$)(?=.*\d)[A-Z0-9]+$/.test(v)}
function barcodeFormats(){return["CODE_128","CODE_39","CODE_93","CODABAR","ITF"].map(x=>window.ZXingBrowser?.BarcodeFormat?.[x]).filter(Number.isInteger)}
function makeReader(){const formats=barcodeFormats(),hints=window.ZXingBrowser?.DecodeHintType?new Map([[ZXingBrowser.DecodeHintType.POSSIBLE_FORMATS,formats],[ZXingBrowser.DecodeHintType.TRY_HARDER,true]]):undefined;return new ZXingBrowser.BrowserMultiFormatReader(hints)}
function releaseCamera(){cameraRequest++;try{cameraControls?.stop()}catch{}cameraControls=null;cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;$("#video").srcObject=null;$("#startCamera").disabled=false;$("#stopCamera").disabled=true}
async function listCameras(){try{const devices=await navigator.mediaDevices.enumerateDevices(),select=$("#cameraSelect"),selected=select.value;select.innerHTML='<option value="">Tự động chọn camera sau</option>';devices.filter(x=>x.kind==="videoinput"&&/back|rear|environment|sau/i.test(x.label)).forEach((x,i)=>{const o=document.createElement("option");o.value=x.deviceId;o.textContent=x.label||"Camera sau "+(i+1);select.appendChild(o)});if([...select.options].some(x=>x.value===selected))select.value=selected}catch{}}
async function openRearCamera(id=""){try{return await navigator.mediaDevices.getUserMedia({audio:false,video:id?{deviceId:{exact:id}}:{facingMode:{exact:"environment"},width:{ideal:1920},height:{ideal:1080}}})}catch(e){if(id)throw e;return navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}}})}}
async function startCamera(){if(session.status!=="open")return;if(!navigator.mediaDevices?.getUserMedia)return setScanStatus("error","Không dùng được camera","Hãy mở trang bằng HTTPS trong Chrome.");if(!window.ZXingBrowser)return setScanStatus("error","Không tải được bộ đọc mã vạch","Kiểm tra mạng rồi tải lại trang.");releaseCamera();const request=++cameraRequest;try{$("#startCamera").disabled=true;setScanStatus("","Đang mở camera sau…","Cho phép quyền camera nếu trình duyệt hỏi.");cameraStream=await openRearCamera($("#cameraSelect").value);if(request!==cameraRequest)return;const video=$("#video");video.srcObject=cameraStream;await video.play();cameraReader=makeReader();cameraControls=await cameraReader.decodeFromStream(cameraStream,video,result=>{if(result&&request===cameraRequest)handleDecoded(result.getText())});$("#stopCamera").disabled=false;setScanStatus("success","Camera sau đang quét","Đưa mã vạch trên thẻ vào khung.");await listCameras()}catch(e){releaseCamera();const msg=e.name==="NotAllowedError"?"Hãy cấp quyền camera cho trang.":e.name==="NotReadableError"?"Camera đang được ứng dụng khác sử dụng.":e.message;setScanStatus("error","Không mở được camera",msg)}}
function handleDecoded(raw){const m=String(raw||"").trim().toUpperCase();if(!validMssv(m))return;const now=Date.now();if(m===lastDecoded&&now-lastDecodedAt<2500)return;lastDecoded=m;lastDecodedAt=now;$("#mssv").value=m;submitCheckin(m)}
function capturePhoto(){const video=$("#video");if(!cameraStream||video.readyState<2)return notice("Vui lòng bật camera trước khi chụp hình.");const canvas=document.createElement("canvas"),scale=Math.min(1,1280/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);pendingPhoto=canvas.toDataURL("image/jpeg",.7);$("#photoPreview").src=pendingPhoto;$("#photoPreviewBox").classList.remove("hidden");notice("Đã chụp hình. Nhập MSSV để lưu kèm ảnh.")}
async function submitCheckin(raw){if(session.status!=="open")return;const m=String(raw||"").trim().toUpperCase();if(!validMssv(m)){feedback("duplicate");return setScanStatus("warn","MSSV không hợp lệ","MSSV gồm 8–12 chữ hoặc số.");}const rosterDoc=await getDoc(doc(db,"attendanceRoster",session.id+"_"+m));if(!rosterDoc.exists()){feedback("duplicate");return setScanStatus("error","Không tìm thấy sinh viên","MSSV không có trong danh sách đối chiếu.");}const checkinRef=doc(db,"checkins",session.id+"_"+m),existing=await getDoc(checkinRef);if(existing.exists()&&!existing.data().deletedAt){feedback("duplicate");return setScanStatus("warn","Đã điểm danh trước đó",m+" · "+(existing.data().name||""));}const p=rosterDoc.data(),data={sessionId:session.id,eventId:session.eventId||"",mssv:m,name:p.name,email:p.email||"",studentUid:p.uid||"",scannerUid:user.uid,scannerEmail:user.email,scannerMssv:user.email.split("@")[0].toUpperCase(),scannerName:assignment.name,checkedAt:serverTimestamp(),deletedAt:null};if(pendingPhoto)data.photoData=pendingPhoto;await setDoc(checkinRef,data);pendingPhoto="";$("#photoPreviewBox").classList.add("hidden");$("#mssv").value="";feedback();setScanStatus("success","Điểm danh thành công",m+" · "+p.name)}
$("#startCamera").onclick=startCamera;$("#stopCamera").onclick=releaseCamera;$("#cameraSelect").onchange=()=>{if(cameraStream)startCamera()};$("#capturePhoto").onclick=capturePhoto;$("#discardPhoto").onclick=()=>{pendingPhoto="";$("#photoPreviewBox").classList.add("hidden")};window.addEventListener("pagehide",releaseCamera);
$("#scanForm").onsubmit=async e=>{e.preventDefault();await submitCheckin($("#mssv").value)};

document.addEventListener("click",async e=>{const b=e.target.closest("[data-delete]");if(!b||assignment.role!=="leader"||session.status!=="open")return;await setDoc(doc(db,"checkins",b.dataset.delete),{deletedAt:serverTimestamp(),deletedByUid:user.uid,deletedByEmail:user.email},{merge:true});notice("Đã xóa lượt điểm danh.")});