import { initializeApp } from "https://www.gstatic.com/firebasejs/11.9.1/firebase-app.js";
import { getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.9.1/firebase-auth.js";
import { getFirestore,collection,doc,getDoc,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,serverTimestamp,Timestamp } from "https://www.gstatic.com/firebasejs/11.9.1/firebase-firestore.js";
import { firebaseConfig,OWNER_EMAIL } from "../firebase-config.mjs";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});const $=s=>document.querySelector(s);let user=null,isOwner=false,events=[],regs=[],admins=[],settings={maxRegistrations:1,allowCancellation:false};
const safe=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const ts=v=>v?.toDate?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(v.toDate()):"";const notice=(m,t="")=>{const n=$("#adminNotice");n.textContent=m;n.className=`notice ${t}`;n.classList.remove("hidden");setTimeout(()=>n.classList.add("hidden"),5000)};
async function hasAccess(u){if(u.email.toLowerCase()===OWNER_EMAIL)return true;return (await getDoc(doc(db,"admins",u.email.toLowerCase()))).exists()}
function render(){$("#metricEvents").textContent=events.length;$("#metricOpen").textContent=events.filter(e=>e.status==="open").length;$("#metricRegs").textContent=regs.length;$("#eventRows").innerHTML=events.map(e=>{const canDelete=(e.registeredCount||0)===0&&(isOwner||e.createdByUid===user.uid),reason=(e.registeredCount||0)>0?"Không thể xóa sự kiện đã có đăng ký":"Chỉ xóa sự kiện do mình tạo";return `<tr><td><b>${safe(e.title)}</b><br><small>${safe(e.location)}</small></td><td>${safe(e.date)}<br>${safe(e.startTime||"")}</td><td>${e.registeredCount||0}/${e.capacity}</td><td>${safe(e.createdByName||e.createdByEmail)}</td><td><span class="tag ${e.status==="open"?"open":"closed"}">${e.status==="open"?"ĐANG MỞ":"ĐÃ ĐÓNG"}</span></td><td><div class="actions"><button class="btn btn-small" data-edit="${e.id}">Sửa</button><button class="btn btn-small btn-danger" data-delete="${e.id}" ${canDelete?"":`disabled title='${reason}'`}>Xóa</button></div></td></tr>`}).join("");$("#eventFilter").innerHTML='<option value="">Tất cả sự kiện</option>'+events.map(e=>`<option value="${e.id}">${safe(e.title)}</option>`).join("");renderRegs();if(isOwner)$("#adminRows").innerHTML=admins.map(a=>`<tr><td>${safe(a.name||"")}</td><td>${safe(a.email)}</td><td>${ts(a.addedAt)}</td><td><button class="btn btn-small btn-danger" data-remove-admin="${safe(a.email)}">Xóa</button></td></tr>`).join("")}
function renderRegs(){const f=$("#eventFilter").value;const list=f?regs.filter(r=>r.eventId===f):regs;$("#regRows").innerHTML=list.map((r,i)=>`<tr><td>${i+1}</td><td><b>${safe(r.identifier||r.mssv)}</b></td><td>${safe(r.name)}</td><td>${safe(r.participantType||"Sinh viên")}</td><td>${safe(r.email)}</td><td>${safe(r.eventTitle)}</td><td>${ts(r.createdAt)}</td></tr>`).join("")}
function listen(){onSnapshot(doc(db,"settings","main"),s=>{if(s.exists())settings={...settings,...s.data()};$("#maxRegistrations").value=settings.maxRegistrations;$("#allowCancellation").checked=!!settings.allowCancellation});onSnapshot(query(collection(db,"events"),orderBy("createdAt","desc")),s=>{events=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(query(collection(db,"registrations"),orderBy("createdAt","desc")),s=>{regs=s.docs.map(d=>({id:d.id,...d.data()}));render()});if(isOwner)onSnapshot(collection(db,"admins"),s=>{admins=s.docs.map(d=>({id:d.id,...d.data()}));render()})}
const inputDateTime=v=>{if(!v)return"";const d=v?.toDate?v.toDate():new Date(v);if(Number.isNaN(d.getTime()))return"";const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};
function openEvent(e=null){$("#eventForm").reset();$("#eventFormError").classList.add("hidden");$("#eventId").value=e?.id||"";$("#eventDialogTitle").textContent=e?"Chỉnh sửa sự kiện":"Tạo sự kiện";for(const k of ["title","description","date","location","startTime","endTime","capacity","status"])if(e&&$("#"+k))$("#"+k).value=e[k]??"";if(e){$("#openAt").value=inputDateTime(e.openAt);$("#closeAt").value=inputDateTime(e.closeAt)}if(!e)$("#status").value="open";$("#eventDialog").showModal()}
$("#eventForm").onsubmit=async ev=>{ev.preventDefault();const submit=ev.submitter,error=$("#eventFormError");submit.disabled=true;submit.textContent="Đang lưu…";error.classList.add("hidden");const id=$("#eventId").value,data={};for(const k of ["title","description","date","location","startTime","endTime","status"])data[k]=$("#"+k).value.trim();data.openAt=$("#openAt").value?Timestamp.fromDate(new Date($("#openAt").value)):null;data.closeAt=$("#closeAt").value?Timestamp.fromDate(new Date($("#closeAt").value)):null;data.capacity=Number($("#capacity").value);data.updatedAt=serverTimestamp();try{if(data.openAt&&data.closeAt&&data.openAt.toMillis()>=data.closeAt.toMillis())throw Error("Giờ đóng phải sau giờ mở đăng ký.");if(id){const old=events.find(e=>e.id===id);if(data.capacity<(old.registeredCount||0))throw Error("Sức chứa không thể nhỏ hơn số đã đăng ký.");await updateDoc(doc(db,"events",id),data)}else await addDoc(collection(db,"events"),{...data,registeredCount:0,createdByUid:user.uid,createdByEmail:user.email.toLowerCase(),createdByName:user.displayName||"",createdAt:serverTimestamp()});$("#eventDialog").close();notice("Đã lưu sự kiện.","success")}catch(e){error.textContent=e.message||"Không thể lưu sự kiện.";error.classList.remove("hidden")}finally{submit.disabled=false;submit.textContent="Lưu sự kiện"}};
$("#settingsForm").onsubmit=async e=>{e.preventDefault();try{await setDoc(doc(db,"settings","main"),{maxRegistrations:Number($("#maxRegistrations").value),allowCancellation:$("#allowCancellation").checked,participantDomains:["student.tdtu.edu.vn","tdtu.edu.vn"],updatedBy:user.email,updatedAt:serverTimestamp()},{merge:true});notice("Đã lưu thiết lập.","success")}catch(e){notice(e.message,"error")}};
$("#adminForm").onsubmit=async e=>{e.preventDefault();const email=$("#adminEmail").value.trim().toLowerCase();try{await setDoc(doc(db,"admins",email),{email,name:$("#adminName").value.trim(),addedByUid:user.uid,addedAt:serverTimestamp()});e.target.reset();notice("Đã thêm Admin.","success")}catch(e){notice(e.message,"error")}};
document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.pane){document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".pane").forEach(x=>x.classList.toggle("hidden",x.dataset.paneId!==b.dataset.pane))}if(b.dataset.newEvent!==undefined)openEvent();if(b.dataset.close!==undefined)$("#eventDialog").close();if(b.dataset.edit)openEvent(events.find(x=>x.id===b.dataset.edit));if(b.dataset.delete){const ev=events.find(x=>x.id===b.dataset.delete);if(ev&&confirm(`Xóa sự kiện “${ev.title}”?`))try{await deleteDoc(doc(db,"events",ev.id));notice("Đã xóa sự kiện.","success")}catch(err){notice(err.message,"error")}}if(b.dataset.removeAdmin&&confirm(`Xóa quyền Admin của ${b.dataset.removeAdmin}?`))try{await deleteDoc(doc(db,"admins",b.dataset.removeAdmin));notice("Đã xóa Admin.","success")}catch(err){notice(err.message,"error")}});$("#eventFilter").onchange=renderRegs;$("#exportBtn").onclick=()=>{const f=$("#eventFilter").value,list=f?regs.filter(r=>r.eventId===f):regs,rows=list.map((r,i)=>({STT:i+1,"Mã số":r.identifier||r.mssv,"Họ tên":r.name,"Đối tượng":r.participantType||"Sinh viên",Email:r.email,"Sự kiện":r.eventTitle,"Ngày sự kiện":r.eventDate,"Thời gian đăng ký":ts(r.createdAt)}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Đăng ký");XLSX.writeFile(wb,`IFAHr_Danh_sach_${new Date().toISOString().slice(0,10)}.xlsx`)};$("#loginBtn").onclick=()=>signInWithPopup(auth,provider);$("#logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){$("#adminLogin").classList.remove("hidden");$("#adminApp").classList.add("hidden");return}if(!u.emailVerified||!(await hasAccess(u))){await signOut(auth);alert("Tài khoản này chưa được cấp quyền Admin IFAHr.");return}user=u;isOwner=u.email.toLowerCase()===OWNER_EMAIL;$("#accountEmail").textContent=u.email;$("#roleText").textContent=`Quyền hiện tại: ${isOwner?"Chủ sở hữu":"Admin"}`;$("#adminLogin").classList.add("hidden");$("#adminApp").classList.remove("hidden");$("#logoutBtn").classList.remove("hidden");$("#adminNav").classList.toggle("hidden",!isOwner);$("#settingsNav").classList.toggle("hidden",!isOwner);listen()});
