import{initializeApp}from"https://www.gstatic.com/firebasejs/11.9.1/firebase-app.js";import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/11.9.1/firebase-auth.js";import{getFirestore,collection,doc,getDoc,getDocs,setDoc,deleteDoc,onSnapshot,query,where,orderBy,serverTimestamp,writeBatch}from"https://www.gstatic.com/firebasejs/11.9.1/firebase-firestore.js";import{firebaseConfig,OWNER_EMAIL}from"../firebase-config.mjs";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);let user,role="",events=[],sessions=[],filter="open",selected=null,roster=[];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const stamp=v=>v?.toDate?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(v.toDate()):"—";const code=()=>crypto.getRandomValues(new Uint32Array(2)).reduce((s,n)=>s+n.toString(36),"").slice(0,9).toUpperCase();const mssvFromEmail=e=>String(e||"").split("@")[0].toUpperCase();
function notice(t){$("#notice").textContent=t;$("#notice").classList.remove("hidden");setTimeout(()=>$("#notice").classList.add("hidden"),3500)}
function label(s){return s==="open"?"Đang mở":s==="ended"?"Đã kết thúc":"Đã chốt danh sách"}
function render(){const byEvent=new Map(sessions.map(s=>[s.eventId,s]));const list=events.filter(e=>!e.deletedAt&&!["Sự kiện Trường","Sự kiện Khoa khác"].includes(e.category)).map(e=>({e,s:byEvent.get(e.id)})).filter(({s})=>filter==="all"||(s?.status||"open")===filter);$("#rows").innerHTML=list.length?list.map(({e,s})=>`<article class="att-row"><div><span class="att-badge ${s?.status||"open"}">${s?label(s.status):"Chưa tạo điểm danh"}</span><h3>${esc(e.title)}</h3><div class="att-meta">${esc(e.date||"")} · ${esc(e.location||"")} · ${Number(e.registeredCount||0)} đăng ký</div></div><div class="att-actions">${s?`<button class="att-btn" data-manage="${s.id}">Quản lý điểm danh</button>`:`<button class="att-btn green" data-create="${e.id}">Đưa sang điểm danh</button>`}</div></article>`).join(""):'<div class="att-card att-empty">Không có sự kiện trong bộ lọc này.</div>'}
async function createSession(eventId){const e=events.find(x=>x.id===eventId);if(!e)return;const id=code(),batch=writeBatch(db);batch.set(doc(db,"attendanceSessions",id),{eventId:e.id,title:e.title,date:e.date||"",location:e.location||"",status:"open",createdByUid:user.uid,createdByEmail:user.email,createdAt:serverTimestamp()});const regs=await getDocs(query(collection(db,"registrations"),where("eventId","==",e.id)));regs.forEach(r=>{const d=r.data(),m=String(d.identifier||d.mssv||"").toUpperCase();if(m)batch.set(doc(db,"attendanceRoster",id+"_"+m),{sessionId:id,eventId:e.id,mssv:m,name:d.name||"",email:d.email||"",uid:d.uid||"",createdAt:serverTimestamp()})});await batch.commit();notice("Đã tạo điểm danh và chuyển danh sách đăng ký.");}
async function manage(id){selected=sessions.find(x=>x.id===id);if(!selected)return;$("#manageTitle").textContent=selected.title;$("#manageMeta").textContent=label(selected.status);const ownerAdmin=role==="owner"||role==="admin";$("#finalizeSession").disabled=!ownerAdmin||selected.status==="finalized";$("#endSession").disabled=selected.status!=="open";$("#reopenSession").classList.toggle("hidden",!ownerAdmin||selected.status!=="finalized");$("#scannerForm").classList.toggle("hidden",selected.status!=="open");$("#grantedByHead").classList.toggle("hidden",role==="subadmin");$("#manageDialog").showModal();await loadManage();}
async function loadManage(){const [a,c,r,g]=await Promise.all([getDocs(query(collection(db,"scannerAssignments"),where("sessionId","==",selected.id))),getDocs(query(collection(db,"checkins"),where("sessionId","==",selected.id))),getDocs(query(collection(db,"attendanceRoster"),where("sessionId","==",selected.id))),role==="subadmin"?Promise.resolve({docs:[]}):getDocs(query(collection(db,"attendanceGrants"),where("sessionId","==",selected.id)))]);roster=r.docs.map(x=>x.data());const grants=new Map(g.docs.map(x=>[x.id,x.data()]));$("#scannerRows").innerHTML=a.docs.map(x=>{const d=x.data(),grant=grants.get(x.id)||{};return`<tr><td>${esc(d.mssv)}</td><td>${esc(d.name)}</td><td>${d.role==="leader"?"SV Leader":"SV quét"}</td><td class="${role==="subadmin"?"hidden":""}">${esc(grant.grantedByName||grant.grantedByEmail||"")}</td><td><button class="att-btn" data-remove-assignment="${x.id}">Xóa</button></td></tr>`}).join("")||'<tr><td colspan="5">Chưa cấp quyền.</td></tr>';$("#checkinRows").innerHTML=c.docs.filter(x=>!x.data().deletedAt).map(x=>{const d=x.data();return`<tr><td>${esc(d.mssv)}</td><td>${esc(d.name)}</td><td>${stamp(d.checkedAt)}</td><td>${esc(d.scannerName||d.scannerMssv)}</td></tr>`}).join("")||'<tr><td colspan="4">Chưa có lượt điểm danh.</td></tr>'}
onAuthStateChanged(auth,async u=>{user=u;$("#loginBtn").classList.toggle("hidden",!!u);$("#logoutBtn").classList.toggle("hidden",!u);$("#app").classList.toggle("hidden",!u);if(!u)return;const a=await getDoc(doc(db,"admins",u.email));role=u.email===OWNER_EMAIL?"owner":a.data()?.role||"";if(!role){await signOut(auth);return notice("Tài khoản chưa được cấp quyền quản lý.");}const eq=role==="subadmin"?query(collection(db,"events"),where("createdByUid","==",u.uid)):collection(db,"events");onSnapshot(eq,s=>{events=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(collection(db,"attendanceSessions"),s=>{sessions=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>role!=="subadmin"||x.createdByUid===u.uid);render()})});
$("#loginBtn").onclick=()=>signInWithPopup(auth,provider).catch(e=>notice(e.message));$("#logoutBtn").onclick=()=>signOut(auth);document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll(".att-filter").forEach(x=>x.classList.toggle("active",x===b));render()}if(b.dataset.create)try{await createSession(b.dataset.create)}catch(x){notice(x.message)}if(b.dataset.manage)manage(b.dataset.manage);if(b.dataset.close!==undefined)$("#manageDialog").close();if(b.dataset.removeAssignment){await deleteDoc(doc(db,"scannerAssignments",b.dataset.removeAssignment));await loadManage()}});
$("#copyScanLink").onclick=()=>navigator.clipboard.writeText(location.origin+"/check-in/?e="+selected.id).then(()=>notice("Đã sao chép link điểm danh."));
$("#endSession").onclick=async()=>{await setDoc(doc(db,"attendanceSessions",selected.id),{status:"ended",endedAt:serverTimestamp()},{merge:true});$("#manageDialog").close()};
$("#finalizeSession").onclick=async()=>{if(!confirm("Sau khi chốt sẽ không thể chỉnh sửa danh sách. Bạn có chắc muốn tiếp tục?"))return;await setDoc(doc(db,"attendanceSessions",selected.id),{status:"finalized",finalizedAt:serverTimestamp(),finalizedBy:user.email},{merge:true});$("#manageDialog").close()};
$("#reopenSession").onclick=async()=>{await setDoc(doc(db,"attendanceSessions",selected.id),{status:"ended",reopenedAt:serverTimestamp(),reopenedBy:user.email},{merge:true});$("#manageDialog").close()};
$("#scannerForm").onsubmit=async e=>{e.preventDefault();const q=$("#scannerLookup").value.trim().toLowerCase();const p=roster.find(x=>x.mssv.toLowerCase()===q||x.name.toLowerCase()===q);if(!p)return notice("Không tìm thấy sinh viên trong danh sách đăng ký.");const email=p.email||p.mssv.toLowerCase()+"@student.tdtu.edu.vn";await setDoc(doc(db,"scannerAssignments",selected.id+"_"+email),{sessionId:selected.id,email,mssv:p.mssv,name:p.name,role:$("#scannerRole").value,active:true,grantedAt:serverTimestamp()});await setDoc(doc(db,"attendanceGrants",selected.id+"_"+email),{sessionId:selected.id,assignmentId:selected.id+"_"+email,grantedAt:serverTimestamp(),grantedByEmail:user.email,grantedByName:user.displayName||user.email});$("#scannerLookup").value="";await loadManage();notice("Đã cấp quyền.")};